[package]
name = "tRustyProbability"
version = "0.1.0"
authors = ["Polyhistorian <root@csyxy.fi>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11" }
rand = { version = "0.8", features = ["log"] }

[profile.release]
lto = true
